### ISSUE TITLE
solution profile

### ISSUE THREAD

**Issue by Kiarashmpr** [BinWang0213/PyGRDECL#1]
Dear Wang,
Many thanks for the library. I also wish to visualize my solution on your existing code. 
Here's my solution for 4 different layer ( solution for the dome reservoir at time 500) and would like to add the functionality to the existing code to generate also the solution on the vtk file. Many thanks.

**Comment by BinWang0213** [comment]
Hi. I did't see any file. Can you upload one by drag it here?

**Comment by Kiarashmpr** [comment]
[
[Temp500.txt](https://github.com/BinWang0213/PyGRDECL/files/2808232/Temp500.txt)
[temp1000.txt](https://github.com/BinWang0213/PyGRDECL/files/2808233/temp1000.txt)

](url)

Hi Wang,
I actually introduce the new keyword [Temp] in your code and in the dome input file also include Temp data. But what i want to see is actually the time series. In other words, i mean how my solution varies by time. I attached my solution for you for two time =500, 1000 and i wish to visualize how solution varies by playing it in paraview.

**Comment by BinWang0213** [comment]
Hi Kiarash,

Please check my updates in GettingStart notebook. I loaded the temperature you provided for the dome case.

Sorry about the later updates.


Thanks,
Bin
