### ISSUE TITLE
ACTNUM does not work

### ISSUE THREAD

**Issue by behzaadh** [BinWang0213/PyGRDECL#4]
My inactive cells still are visible in the PARAVIEW!

**Comment by BinWang0213** [comment]
Hi,

As some GRDECL file doesn't have **ACTNUM**, so I didn't load it by default.

You can use `LoadCellData()` to load ACTNUM from the file explicitly. And then using `Threshold` function in Paraview to obtain a VTU file without inactive cells (ACTNUM=0).

```python
data='./ExampleData/Johansen.grdecl'
Model=GeologyModel(filename=data)
Model.LoadCellData(varname="ACTNUM",filename=data)

Model.GRDECL2VTK()
Model.Write2VTU()
```
![image](https://user-images.githubusercontent.com/20053787/101272034-23a62580-374e-11eb-92fb-ae31af07ca47.png)
![image](https://user-images.githubusercontent.com/20053787/101272036-302a7e00-374e-11eb-8b41-0cb0d237924b.png)

**Comment by behzaadh** [comment]
Thanks, @BinWang0213, for your response. Actually, I already did what you mentioned. I thought it might have been implemented by default.
